server:
  port: 9999

spring:
  application:
    name: dearoffer-zuul
  redis:
    host: 106.12.117.44
eureka:
  client:
    serviceUrl:
      defaultZone: http://129.28.154.216:8686/eureka/
  instance:
    prefer‐ip‐address: true

zuul:
  routes:
    dearoffer-auth:
      path: /base/**
      serviceId: dearoffer-auth
    dearoffer-post:
      path: /post/**
      serviceId: dearoffer-post
    dearoffer-search:
      path: /search/**
      serviceId: dearoffer-search
  host:
    connect-timeout-millis: 8000
    socket-timeout-millis: 8000
ribbon:
  ReadTimeout: 8000
  ConnectTimeout: 8000

