server:
  port: 9002

spring:
  application:
    name: dearoffer-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.230.129:3306/offer?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true

  redis:
    host: 192.168.230.129

  rabbitmq:
    host: 192.168.230.129

redis:
  keys:
    register_code_fix: 'register:code:phone_'

message:
  register:
    effectiveTime: 2