spring:
  application:
    name: dearoffer-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/javakk/dearoffer-config.git
  rabbitmq:
    host: 129.28.154.216


management:
  endpoints:
    web:
      exposure:
        include: bus‐refresh

server:
  port: 12000