server:
  port: 9001

spring:
  application:
    name: dearoffer-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.230.129:3306/offer?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true