server:
  port: 9005
spring:
  application:
    name: dearoffer-post
  data:
    mongodb:
      database: commentdb
      host: 192.168.230.128
  redis:
    host: 192.168.230.128

eureka:
  client:
    service‐url:
    defaultZone: http://localhost:8686/eureka
  instance:
    prefer‐ip‐address: true