server:
  port: 9999

spring:
  application:
    name: dearoffer-company
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://180.76.57.187:3306/offer?characterEncoding=utf-8
    username: root
    password: JavaKK1024
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  redis:
    host: 106.12.117.44